# Global Configs

SCREEN_WIDTH = 240
SCREEN_HEIGHT = 160
FPS = 15

GAME_TITLE = "Rubik's Evo Portaland"

STAGE_LEVEL_WIDTH_TILES = 16
STAGE_LEVEL_HEIGHT_TILES = 16
STAGE_LEVEL_ONE_TILE_WIDTH = 8
STAGE_LEVEL_ONE_TILE_HEIGHT = 8

STAGE_LEVEL_PIXEL_WIDTH = STAGE_LEVEL_WIDTH_TILES * STAGE_LEVEL_ONE_TILE_WIDTH
STAGE_LEVEL_PIXEL_HEIGHT = STAGE_LEVEL_HEIGHT_TILES * STAGE_LEVEL_ONE_TILE_HEIGHT

STAGE_UPPER_LEFT_X = (SCREEN_WIDTH - STAGE_LEVEL_PIXEL_WIDTH) / 2
STAGE_UPPER_LEFT_Y = (SCREEN_HEIGHT - STAGE_LEVEL_PIXEL_HEIGHT) / 2

STAGE_TRANSPARENT_COLOR = 0

SCREEN_SHAKE_MAGNITUDE = 4

WALL_TILE = (1, 0)